### ISSUE TITLE
daemon mode implies batch mode?

### ISSUE THREAD

**Issue by gonzoleeman** [open-iscsi/targetcli-fb#160]
Thanks for all the great work you guys have done on targetcli-fb!

I just tested the latest targetcli-fb, particularly the daemon mode, and I was surprised. Perhaps I missed the announcement of the change in architecture around the daemon.

Evidently daemon mode now means you can't run targetcli interactively without adding a "no daemon" flag each and every time. That makes daemon node useless to me and to my users. Why did you make that change? This means the daemon will almost never be used. I'm certainly not going to enable the daemon systemd service by default.

Even doing something as simple as "targetcli ls /" from the shell gives different results if you are in daemon mode vs non-daemon mode. In daemon mode, all the color highlighting is gone.

It seem like "daemon mode" and "batch mode" have become one. Can we back up and make that two different things? I get the idea of using a daemon to make things faster, but that should not require batch mode.

The whole design of the deamon was "interesting", as was mostly a copy of targetcli. That seemed a little wasteful to me, but I understood it's simplicity. But isn't the proper way to architect this to have a daemon that does all the work, and a user-level command that talks to it, ala iscsiadm and iscsid for open-iscsi?

**Comment by pkalever** [comment]
I thought you understood it first before anyone else, and I was happy to see your review comments at the initial PR request https://github.com/open-iscsi/targetcli-fb/pull/132

But I’m also happy that you opened this issue, hope this will be a place keeper for newbies to understand the need for a daemon component.

For me, I would say daemon mode solved a lot of scalability issues for us at production. Our tool invokes targetcli each time a new create/delete/modify (storage objects/targets) configuration requests kicks in. At a large scale like 1000 configuration objects on the system, the targetcli requests are delayed a lot (this took up to few mins in the worst case, I have seen more than 5 mins response time). Unfortunately, the existing targetcli batch mode and interactive mode doesn't solve this completely, as they need to scan through the entire targets on the system and only then get back to actual work, even loading the config once (assume there are already 1000 block volume configs) for running single bunch (set of commands grouped) of commands take too long. Hence we decided to do something about this without effecting the current users of targetcli upstream.

Some challenges were to keep:
* The design change as much simple as possible.
* Keep the changes minimal and reuse the code, so that there is very minimal possibility of regressions.
* Maintain interface compatibility with exiting applications/users.
* Allow fall-back mechanism to CLI mode.


What modes are offered by CLI-mode (default):
* Just run '# targetcli <CMD>' and get the output
* Interactive mode
* Batch mode, like
 ‘# targetcli << BATCH
 cmd1
 cmd2
 cmd3
 .
 .
 cmdN
 BATCH’


What modes are offered by daemonized-mode:
* Jun run '# targetcli <CMD>' and get the output
   [Each cmd will go though targetclid, avoiding the need to scan complete existing targets]
* Batch mode, like
  \# targetcli <enter>
  \> cmd1
  \> cmd2
  \> cmd3
  \> .
  \> .
  \> exit


How to enable/disable cli/daemonized modes permenently?
Enable:
\# systemctl start targetclid.socket  [one time]
\# systemctl enable targetclid.socket [one time]
\# targetcli set global auto_use_daemon=true

Disable:
\# targetcli --disable-daemon
(or)
\# targetcli set global auto_use_daemon=false

Also there is a man page entry for targetclid, please take a look at it for more details.


Does targetcli daemonized mode support interactive mode?
No, although its very simple to implement, I expect nothing different than what's done in the CLI mode. But if we feel unhappy, switching between cli and daemon modes every time someone want to use interactive mode, then I'm ok to bring interactive mode to daemonized approach.

Does targetcli daemonized mode has a coloring output feature?
No, I'm personally not a big fan of it, also in our case almost we never see the output, it’s our tool which parses the targetcli output and converts into something simple. But I will be happy to welcome such changes, also will do my best with the reviews and testing those patches.

Also please note that there is a lot of scope to improve the daemon to make it work much better, IMHO it's still at its 1.0v tag.

Thanks!

**Comment by gonzoleeman** [comment]
I appreciate that batch mode is much more efficient, but I thought the idea of the daemon was to make interactive more efficient, as well, cutting down on startup time.

There is no value whatsoever, that I can see, in using targetcli interactively in batch mode. I can see the following use cases:
- batch mode -- for doing a lot of configuration from outside targetcli (like from a shell script), for large scale configuration, where it'd be much faster
- interactive mode -- where I get the regular targetcli

Right now, I have to disable the daemon the get interactive mode.

The first version of the daemon code you created did not act like this, hence my current surprise.

I will advise my users to stay away from daemon mode unless they are doing large-scale scripting and configuration. I realize some sysadm solutions will use this large-scale batch approach, but those users are other products, not people. Sometimes real people (like me) want to use targetcli, and evidently daemon mode makes that impossible.

I consider it a bug that daemon mode implies batch mode, and if and when I get a chance, I'll submit a patch to fix that bug.

**Comment by iammattcoleman** [comment]
@gonzoleeman I completely agree: the targetcli shell should always be interactive, regardless of whether the daemon is used. I've been considering fixing this, as well. Have you started on it yet?

**Comment by pkalever** [comment]
> @gonzoleeman I completely agree: the targetcli shell should always be interactive, regardless of whether the daemon is used. I've been considering fixing this, as well. Have you started on it yet?

@gonzoleeman may be a good news for you :-)

@iammattcoleman I have the initial working code on my laptop will consider sending it live after I wake up in the morning.

It works something like:

```
$ targetcli -i
> pwd
/
> cd /iscsi/
> pwd
/iscsi
> exit
```

It needs -i or --interactive option, as default without any option enters into batch mode now.

Thanks!
\-\-
Prasanna
Sent from my mobile.

**Comment by iammattcoleman** [comment]
I think the default should be interactive, so `targetcli`'s behavior is consistent regardless of whether it's using the daemon.

**Comment by gonzoleeman** [comment]
No, I had not tried to fix it yet. I thought there we no support for fixing it, but I'm glad I was incorrect. Please let me know if I can test or help.
