### ISSUE TITLE
Question: how to safely reboot a target? 

### ISSUE THREAD

**Issue by Forza-tng** [open-iscsi/targetcli-fb#185]
What is the correct way to stop and restart the iscsi target server (fileio backing) to ensure all data is flushed to disk?

**Comment by gonzoleeman** [comment]
Do you mean targetclid?

**Comment by maurizio-lombardi** [comment]
targetcli has no control over the I/O because the LIO target is entirely implemented in kernel.

With reboot you mean rebooting the machine? Assuming that all the initiators are disconnected, it's always safe to reboot the target server machine, the kernel takes care of flushing the caches before shutting itself down.

**Comment by Forza-tng** [comment]
I believe my problem was that I was using FileIO and the rebooting cause a circular dependency - i.e. stopping local filesystem could not happen because of open file by LIO, so system eventually forced a reboot and so stuff in write cache got lost. We can close this issue.
