### ISSUE TITLE
pSCSI freeze system

### ISSUE THREAD

**Issue by francescoemiliani** [open-iscsi/targetcli-fb#203]
Hi, I'm trying to share my BD and Tape drive (not tried yet) over iscsi (and FC, but currently all HBA are not available for my test). I try this barebone (a supermicro motherboard), and in a VM. The result are the same. I can't play too much with real hardware so, this is my test with VM.

I try to expose **a disk with block backstore**, no issue, all **works** good.

When I try to **expose my BD drive** (or, in this case, a virtual VM CDROM drive) with **pSCSI backstore**, something not works. **I can login with initiator**, lsscsi works, lsblk the same (also show correctly medium size), but i can't access the device. When I try to mount (or pv, dd), it hangs for a while, then **"no medium found"**. The output of dmesg of the target machine is not happy, there are some errors:

```
db_root: cannot open: /etc/target 
pSCSI: failed to append bio
```

This is a more complete output: https://pastebin.com/3Vjhkejw

I try this in Debian, archlinux (with the latest version of targetcli) and rockylinux (that freeze completely). Can be something about the kernel driver?

I wish you a pleasant day!

PS: sorry for my language... I'm a disaster

**Comment by gonzoleeman** [comment]
I have shared a tape drive via pSCSI before, but it's been a few years.

The message you are asking about isn't from any tape-specific issue. This message is because rtslib-fb is trying to set your database root directory to /etc/target, but the directory does not exist. This is where your backups go for your targetcli configuration, and where saveconfig.json goes. Try "mkdir /etc/target". The rtslib-fb package should have created this directory when you installed it. (I actually wrote this code, so it's familiar.) How did you install the rtslib-fb package?

As far as your SCSI problems, I'm not sure what the issue is, but your kernel seems to dislike something you are doing with pSCSI. I would check with your distribution. Do you have the latest or a recent kernel? What command(s) are you using to talk to the tape drive once it shows up remotely? Does "mt status" work on it? As far as distributions, I used Tumbleweed when I did my proof of concept for a Linux Conference. But it sounds like you're setting it up correctly ...

**Comment by maurizio-lombardi** [comment]
This is not a problem in rtslib/targetcli but at lower level (kernel), also you should consider the fact that pSCSI means passthrough  (passthrough of commands without emulation) and this is known to not work well with some devices

**Comment by francescoemiliani** [comment]
many thanks for your reply! Yes I know that pscsi is a passthrought, several years ago I have this exactly box with the same identical hardware (except cpu and ram), and works fine! I was interested in ZFS then I moved all iSCSI and FC to Solaris. Now ZFS works very well on linux, and with the new oracle policies (CBE release instead of GA), I wanted to go back to Linux, but now there are trouble with SCSI, I'm lucky!! In these years evidently something has changed in the linux kernel, thanks again for your kindly replys!
