### ISSUE TITLE
name 'glob' is not defined

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [open-iscsi/targetcli-fb#206]
Hi in latest release of opensuse Tubmleweed when i try to do anything with targetcli other than display help i am getting "name 'glob' is not defined", nothing else. I noticed that version was 57 not 58 but that didn't fix it. Any suggestions?

Thanks

**Comment by gonzoleeman** [comment]
This is a problem with the SUSE version of targetcli, not upstream. The problem was actually an incorrect patch being added to rtslib-fb in Tumbleweed, in an attempt to remove our dependency on Python2, but it was not applied correctly or tested. The patch in question has been reverted. I believe this is fixed now in Tumbleweed.

**Comment by gonzoleeman** [comment]
Closing, since I just tested latest tumbleweed, and this is indeed fixed.

**Comment by Michal-Szczepaniak** [comment]
Thanks and sorry for bothering!

**Comment by maurizio-lombardi** [comment]
@gonzoleeman  Thanks for looking at it
